// Each AI account's mark as a PNG (made from web/src/logos.ts by `node scripts/icons.mjs`); Metro needs literal requires.
export const MARKS: Record<string, number> = {
  chatgpt: require('../assets/ai/chatgpt.png'),
  grok: require('../assets/ai/grok.png'),
  copilot: require('../assets/ai/copilot.png'),
  openrouter: require('../assets/ai/openrouter.png'),
  minimax: require('../assets/ai/minimax.png'),
  claude: require('../assets/ai/claude.png'),
};
// Chief and each helper as PNGs (made from web/src/art.ts by `node scripts/icons.mjs`): whole in every pose for the
// office, `head-` for faces. Metro needs literal requires, so the phone reads PALS[`${who}-${pose}`].
export const PALS: Record<string, number> = {
  'chief-listen': require('../assets/pals/chief-listen.png'),
  'head-chief-listen': require('../assets/pals/head-chief-listen.png'),
  'reel-listen': require('../assets/pals/reel-listen.png'),
  'head-reel-listen': require('../assets/pals/head-reel-listen.png'),
  'scout-listen': require('../assets/pals/scout-listen.png'),
  'head-scout-listen': require('../assets/pals/head-scout-listen.png'),
  'scribe-listen': require('../assets/pals/scribe-listen.png'),
  'head-scribe-listen': require('../assets/pals/head-scribe-listen.png'),
  'tracer-listen': require('../assets/pals/tracer-listen.png'),
  'head-tracer-listen': require('../assets/pals/head-tracer-listen.png'),
  'pip-listen': require('../assets/pals/pip-listen.png'),
  'head-pip-listen': require('../assets/pals/head-pip-listen.png'),
  'chief-work': require('../assets/pals/chief-work.png'),
  'head-chief-work': require('../assets/pals/head-chief-work.png'),
  'reel-work': require('../assets/pals/reel-work.png'),
  'head-reel-work': require('../assets/pals/head-reel-work.png'),
  'scout-work': require('../assets/pals/scout-work.png'),
  'head-scout-work': require('../assets/pals/head-scout-work.png'),
  'scribe-work': require('../assets/pals/scribe-work.png'),
  'head-scribe-work': require('../assets/pals/head-scribe-work.png'),
  'tracer-work': require('../assets/pals/tracer-work.png'),
  'head-tracer-work': require('../assets/pals/head-tracer-work.png'),
  'pip-work': require('../assets/pals/pip-work.png'),
  'head-pip-work': require('../assets/pals/head-pip-work.png'),
  'chief-needs': require('../assets/pals/chief-needs.png'),
  'chief-wave': require('../assets/pals/chief-wave.png'),
  'head-chief-needs': require('../assets/pals/head-chief-needs.png'),
  'reel-needs': require('../assets/pals/reel-needs.png'),
  'head-reel-needs': require('../assets/pals/head-reel-needs.png'),
  'scout-needs': require('../assets/pals/scout-needs.png'),
  'head-scout-needs': require('../assets/pals/head-scout-needs.png'),
  'scribe-needs': require('../assets/pals/scribe-needs.png'),
  'head-scribe-needs': require('../assets/pals/head-scribe-needs.png'),
  'tracer-needs': require('../assets/pals/tracer-needs.png'),
  'head-tracer-needs': require('../assets/pals/head-tracer-needs.png'),
  'pip-needs': require('../assets/pals/pip-needs.png'),
  'head-pip-needs': require('../assets/pals/head-pip-needs.png'),
  'chief-pleased': require('../assets/pals/chief-pleased.png'),
  'head-chief-pleased': require('../assets/pals/head-chief-pleased.png'),
  'reel-pleased': require('../assets/pals/reel-pleased.png'),
  'head-reel-pleased': require('../assets/pals/head-reel-pleased.png'),
  'scout-pleased': require('../assets/pals/scout-pleased.png'),
  'head-scout-pleased': require('../assets/pals/head-scout-pleased.png'),
  'scribe-pleased': require('../assets/pals/scribe-pleased.png'),
  'head-scribe-pleased': require('../assets/pals/head-scribe-pleased.png'),
  'tracer-pleased': require('../assets/pals/tracer-pleased.png'),
  'head-tracer-pleased': require('../assets/pals/head-tracer-pleased.png'),
  'pip-pleased': require('../assets/pals/pip-pleased.png'),
  'head-pip-pleased': require('../assets/pals/head-pip-pleased.png'),
  'chief-rest': require('../assets/pals/chief-rest.png'),
  'head-chief-rest': require('../assets/pals/head-chief-rest.png'),
  'reel-rest': require('../assets/pals/reel-rest.png'),
  'head-reel-rest': require('../assets/pals/head-reel-rest.png'),
  'scout-rest': require('../assets/pals/scout-rest.png'),
  'head-scout-rest': require('../assets/pals/head-scout-rest.png'),
  'scribe-rest': require('../assets/pals/scribe-rest.png'),
  'head-scribe-rest': require('../assets/pals/head-scribe-rest.png'),
  'tracer-rest': require('../assets/pals/tracer-rest.png'),
  'head-tracer-rest': require('../assets/pals/head-tracer-rest.png'),
  'pip-rest': require('../assets/pals/pip-rest.png'),
  'head-pip-rest': require('../assets/pals/head-pip-rest.png'),
};
